set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# Format every crate.
fmt:
    cargo fmt --all

# Check formatting without mutating the worktree.
fmt-check:
    cargo fmt --all -- --check

# Cargo build (debug) for the entire workspace.
build:
    cargo build --workspace

# Cargo build (release) for the entire workspace.
build-release:
    cargo build --workspace --release

# Run all unit + integration tests.
test:
    cargo test --workspace

# Type-check without producing binaries.
check:
    cargo check --workspace

# Strict lint pass — the same gate CI uses.
lint:
    cargo clippy --workspace --all-targets -- -D warnings

# `cargo-deny` license + advisory check (requires `cargo install cargo-deny`).
deny:
    cargo deny --all-features check

# Recursive `cargo-audit` against the lockfile (requires `cargo install cargo-audit`).
audit:
    cargo audit

# Regenerate the autogenerated third-party license supplement at
# docs/credits-third-party.md from the current Cargo.lock.
# Requires `cargo install cargo-about --features cli`.
credits:
    cargo about generate about.hbs --output-file docs/credits-third-party.md
    # cargo-about embeds some upstream license texts with CRLF; normalize to
    # LF so the include_str!'d bundle renders cleanly in the in-app viewer.
    sed -i 's/\r$//' docs/credits-third-party.md
    @echo "wrote docs/credits-third-party.md"

# Generate and stamp the man page into target/man/.
manpage:
    mkdir -p target/man
    cargo run -q -p grexa-cli -- manpage > target/man/grexa-cli.1
    @echo "wrote target/man/grexa-cli.1"

# Generate shell completion scripts into target/completions/.
completions:
    mkdir -p target/completions
    cargo run -q -p grexa-cli -- completions bash > target/completions/grexa-cli.bash
    cargo run -q -p grexa-cli -- completions zsh > target/completions/_grexa-cli
    cargo run -q -p grexa-cli -- completions fish > target/completions/grexa-cli.fish
    @echo "wrote target/completions/*"

# `cargo package` for every crate (handy as a release dry-run).
package:
    cargo package --workspace --allow-dirty

# Run the CLI with arbitrary arguments. Example: `just run-cli /tmp TODO --quiet`.
run-cli *args:
    cargo run -p grexa-cli -- {{args}}

# Launch the GUI.
run-gui:
    cargo run -p grexa

# Vendor every cargo dependency into target/flatpak/vendor. Required
# before `just flatpak` so the sandboxed build can compile with no
# network access. Re-runs are cheap (cargo only re-downloads crates
# that aren't already in vendor/). Note: this does NOT touch
# .cargo/config.toml — `just flatpak` writes / removes it around the
# build so host cargo builds aren't redirected at the vendor tree.
flatpak-vendor:
    mkdir -p target/flatpak
    cargo vendor --locked target/flatpak/vendor > target/flatpak/vendor-config.toml
    @echo "wrote target/flatpak/vendor + target/flatpak/vendor-config.toml"

# Build the Flatpak into a local OSTree repo at target/flatpak/repo and
# the install tree at target/flatpak/build. Requires:
#   flatpak-builder
#   org.kde.Platform//6.10
#   org.kde.Sdk//6.10
#   org.freedesktop.Sdk.Extension.rust-stable//25.08
flatpak: flatpak-vendor
    # Stage the vendor config at .cargo/config.toml just long enough for
    # flatpak-builder to copy the source tree into the sandbox, then
    # restore the original so subsequent host cargo builds use the
    # registry cache (and the per-repo sccache+mold acceleration). The
    # trap also fires on failure to keep the worktree clean.
    mkdir -p .cargo
    if [ -f .cargo/config.toml ]; then mv .cargo/config.toml .cargo/config.toml.flatpak-backup; fi
    cp target/flatpak/vendor-config.toml .cargo/config.toml
    trap 'rm -f .cargo/config.toml; if [ -f .cargo/config.toml.flatpak-backup ]; then mv .cargo/config.toml.flatpak-backup .cargo/config.toml; fi' EXIT INT TERM; \
        flatpak-builder --user --force-clean --disable-rofiles-fuse \
            --repo=target/flatpak/repo \
            target/flatpak/build \
            packaging/flatpak/com.visorcraft.Grexa.yml
    @echo "built target/flatpak/repo"

# The container path matters because cxx-qt-build's QML AOT compiler
# links against Qt's private API, which is pinned to the exact Qt
# minor version. An RPM built on Arch / CachyOS (Qt 6.11) fails to
# install on Fedora 44 (Qt 6.9). See packaging/fedora/Containerfile.fedora44.
# Build the Fedora 44 .rpm inside a podman container (Qt 6.9 matched).
fedora-pkg:
    bash packaging/fedora/build-in-container.sh

# Bundle the Flatpak repo into a single redistributable .flatpak file
# at target/release/grexa.flatpak.
flatpak-bundle: flatpak
    mkdir -p target/release
    flatpak build-bundle target/flatpak/repo \
        target/release/grexa.flatpak \
        com.visorcraft.Grexa master
    @echo "wrote target/release/grexa.flatpak"

# Convenience target — everything CI does. Useful before pushing.
ci: fmt-check lint test
    @echo "ci preflight passed"

# Full pre-release gate: ci + deny + audit + credits regen.
preflight: ci deny audit credits
    @echo "preflight passed"
